### ISSUE TITLE
[Error] Incorrect city id.

### ISSUE THREAD

**Issue by diverent2** [lkozyr/weatherium-app#2] opened 2018-07-15 18:38 UTC
I wanted to test your project out but I can´t bc I keep getting an error "incorrect city id"

![ice_screenshot_20180715-202514](https://user-images.githubusercontent.com/24892204/42736920-60dca802-886e-11e8-9758-b0794bbe1c26.png)

PS: I just randomly found your project through a friend and it looked completed to me so I wanted to test it out ^^
So sorry if this project still is WIP and you are already working on these things and don´t need want issues reported yet... 😄

**Comment by lkozyr** [comment] 2018-07-15 18:59
Hey @MaximilianUE, did you download the code and built the project locally? Or did you reach it via production URL (http://weather-app-20180703.epizy.com/)? Please specify the exact URL / steps to reproduce. Thank you.

**Comment by diverent2** [comment] 2018-07-15 20:40
Oh sorry got mixed up with the other issue I´ve opened.
The issue happened to me in the [online version](http://weather-app-20180703.epizy.com/) of the app.
I´m currently trying to set up a local copy for myself and will update you once I know if the issue persists for me locally. Sadly npm is making a lot of problems lately, so it might take a while. 
Maybe you could consider switching to [yarn ](https://yarnpkg.com/lang/en/) instead, it apparently is faster, more reliable and just better overall. Oh and switching to it is pretty easy. 👍

**Comment by diverent2** [comment] 2018-07-15 20:46
[Update:]  see #3

**Comment by lkozyr** [comment] 2018-07-16 13:57
After some research, I believe the issue occurs when for some reason cityData cannot be retrieved from the third party service. I cannot reproduce this on my end, so I am not sure what kind of error is thrown by the service. After checking their [documentation](https://ipstack.com/documentation), it does not look like any of the errors described can cause the issue (e.g. 'No API Key was specified.' or 'The maximum allowed amount of monthly API requests has been reached. '  as everything works fine for me.

As a workaround, instead of showing an error, we'll use a default city to load weather data for, if city cannot be defined by IP for any reason (any http://api.ipstack.com/check API error). Thus user will get the app loaded and may search for their specific city weather using the search box. The app stores 5 last searched cities and will load same cities next time the app is used.

See commit: https://github.com/lkozyr/weatherium-app/commit/306ece4e1937dcc10d902609865da8257591d72a

Closing the issue.

**Closed as completed by lkozyr** 2018-07-16 13:57 UTC
