### ISSUE TITLE
[Error:] Unhandled Rejection (TypeError): Cannot read property 'id' of null

### ISSUE THREAD

**Issue by diverent2** [lkozyr/weatherium-app#3] opened 2018-07-15 20:46 UTC
trying to run the app locally, I get this error
![ice_screenshot_20180715-224058](https://user-images.githubusercontent.com/24892204/42738230-9c0e9e5a-8880-11e8-809a-17fa82dd3722.png)

This is very likely the same on the online version as well, see #2, just not visible bc it´s in production state.

**Comment by flower17** [comment] 2018-07-15 20:57
For some reason cityData is not retrieved for you. I have not faced with this issue on my side. 
However once you try to open a direct city id url, it should work for you, please try: 
http://weather-app-20180703.epizy.com/3221033
This should help if you just want to play with the app.
In the meanwhile I will take a look at why city data retrieval may be failing.

**Comment by lkozyr** [comment] 2018-07-15 21:00
For some reason cityData is not retrieved for you. I have not faced with this issue on my side.
However once you try to open a direct city id url, it should work for you, please try:
http://weather-app-20180703.epizy.com/3221033
This should help if you just want to play with the app.
In the meanwhile I will take a look at why city data retrieval may be failing.

**Comment by lkozyr** [comment] 2018-07-15 21:08
If you'd like to play locally, you should have valid access keys for data providers, for more details please see README.md (https://github.com/lkozyr/weatherium-app/blob/master/README.md), I have updated it with prerequisites info.

**Comment by lkozyr** [comment] 2018-07-16 13:59
Duplicate of https://github.com/lkozyr/weatherium-app/issues/2.
Closing as duplicate.

**Closed as completed by lkozyr** 2018-07-16 13:59 UTC
